#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Aug 07 21:14:34 GMT+07:00 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=5
shaderPack=
