["Couplet Rendering Settings"]
	#对联文字大小 | 默认值: 0.025 | 范围: 0.01-0.05
	textScale = 0.025
	#对联文字水平偏移量 | 正值向右，负值向左 | 默认值: 0.2 | 范围: -1.0-1.0
	horizontalOffset = 0.19999999999999996
	#(2格高)对联文字垂直偏移量 | 正值向上，负值向下 | 默认值: -19.5 | 范围: -100.0-100.0
	doubleBaseY = -19.5
	#(3格高)对联文字垂直偏移量 | 正值向上，负值向下 | 默认值: -39.5 | 范围: -100.0-100.0
	tripleBaseY = -39.5
	#对联文字间距 | 默认值: 9.6 | 范围: 5.0-15.0
	verticalSpacing = 9.6

["Banner Rendering Settings"]
	#横幅文字大小 | 默认值: 0.022 | 范围: 0.01-0.05
	bannerTextScale = 0.022
	#横幅文字垂直偏移量 | 正值向上，负值向下 | 默认值: 2.50 | 范围: -5.0-5.0
	bannerVerticalOffset = 2.5
	#(1格宽)横幅文字水平偏移量 | 正值向右，负值向左 | 默认值: -0.9 | 范围: -50.0-50.0
	bannerSingleOffset = -0.8999999999999986
	#(2格宽)横幅文字水平偏移量 | 正值向右，负值向左 | 默认值: 14.00 | 范围: -50.0-50.0
	bannerDoubleOffset = 14.0
	#(3格宽)横幅文字水平偏移量 | 正值向右，负值向左 | 默认值: 28.9 | 范围: -50.0-50.0
	bannerTripleOffset = 28.900000000000006
	#横幅文字间距 | 默认值: 9.5 | 范围: 5.0-15.0
	bannerCharWidth = 9.5
