version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
kaleidoscope_cookery = true
framedblocks = true
farmersdelight = true
aeroencasedpipe = true
drivebywire = true
someassemblyrequired = true
kaleidoscope_chinesefood = true
brewery = true
refurbished_furniture = true
numismatics = true
brewinandchewin = true
sable_player_ragdoll = true
quark = true
ballastmod = true
another_furniture = true
easyanvils = true
ecologics = true
natures_spirit = true
copycats = true
furniture = true
selling_bin = true
createdieselgenerators = true
create_submarine = true
aeronautics_utility_objects = true
benssharks = true
create_sa = true
fastpaintings = true
railways = true
bellsandwhistles = true
bits_n_bobs = true
amendments = true
createcobblestone = true
herbalbrews = true
chisel = true
moonlight = true
bakery = true
sophisticatedbackpacks = true
alloyed = true
exposure = true
seamlesssleep = true
offroad = true
brick_and_mortar = true
corn_delight = true
create_factory = true
create_ca = true
supplementaries = true
tinymultiblocklib = true
drivebywiretypewriter = true
createprism = true
create = true
culturaldelights = true
aeronautics = true
simulated = true
farm_and_charm = true
interiors = true
vsfluidlink = true
minecraft = true
create_dragons_plus = true
lootr = true
create_connected = true
starcatcher = true
createdeco = true
createaddition = true
powergrid = true
easy_npc = true
createframed = true
tracks = true
vinery = true
delightfulcreators = true
aeroworks = true
create_power_loader = true
