# Don't change this! Version used to track needed updates.
version = 1
disableParticles = false
byTypeReductions = {  }
maxParticlesPerSheet = 3000
particleRenderDistanceMultiplier = 0.4794117647058823
asynchronousTicking = true
reduceAllChance = 0.4019608
reduceDecreasedChance = 0.04901961
turnOffPotionParticlesV2 = [
    "SELF"
]