name = "Funautic"
author = "Kucing"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd5a443154eaf164cbb2e2901071c96757fd92e4adfd35ef209a7c8ec72a671b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
unsup = "1.1.6"
