name = "Funautic"
author = "Kucing"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "279254622599eb872adfcaf936d3373d643290491ae0e4dcdcd260e14f7061ad"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
unsup = "1.1.6"
