name = "Funautic"
author = "Kucing"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9528c484035f32e51b7ccbaaa6188c0fc959c03e191c164284cccd09abb7a92b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
unsup = "1.1.6"
