# Base Pack
[flavor_groups.funautic]
name = "Funautic Pack Choices"
description = "from the ashes became a muara"
side = "both"
[[flavor_groups.funautic.choices]]
id = "funautic_base"
name = "Base Version"
description = "Versi basic cuman mod yang penting aja, cocok buat yang mau main di server SMP"
[[flavor_groups.funautic.choices]]
id = "funautic_fancy"
name = "Fancy Version"
description = "Versi fancy dengan lebih banyak fitur dan visual yang menarik"

# Shader Choices
[flavor_groups.shader]
name = "Shader Choices"
description = "Only Shader dan optimasinya"
side = "client"
[[flavor_groups.shader.choices]]
id = "noshader"
name = "NO Shader"
description = "Tanpa Shader"
[[flavor_groups.shader.choices]]
id = "shader"
name = "Iris Shader"
description = "Shader dan optimasinya"

# Button Choice
[flavor_groups.dh]
name = "Distant Horizon"
side = "client"
choices = ["dh_off", "dh_on"]
[flavor_groups.camtweak]
name = "Camera Tweaks"
side = "client"
choices = ["camera_tweak_off", "camera_tweak_on"]
[flavor_groups.cltweak]
name = "Client Tweaks"
side = "client"
choices = ["tweak_client_off", "tweak_client_on"]
[flavor_groups.soundtweak]
name = "Immersive Sounds"
side = "client"
choices = ["sound_off", "sound_on"]
[flavor_groups.atmospherics]
name = "Atmospherics"
side = "client"
choices = ["atmospherics_off", "atmospherics_on"]
[flavor_groups.tooltips]
name = "Tooltips"
side = "client"
choices = ["tooltips_off", "tooltips_on"]
[flavor_groups.motitweak]
name = "Tweak Motion"
side = "client"
choices = ["tweak_motion_off", "tweak_motion_on"]
[flavor_groups.emftweak]
name = "EMF Compability"
side = "client"
choices = ["emf_comp_off", "emf_comp_on"]
[flavor_groups.punchy]
name = "Punchy"
side = "client"
choices = ["punchy_off", "punchy_on"]
[flavor_groups.admintools]
name = "Admin Tools"
side = "client"
choices = ["admintools_off", "admintools_on"]

# Modlist
[metafile.3dskinlayers]
flavours = "funautic_fancy"
[metafile.better-clouds]
flavours = "funautic_fancy"
[metafile.blur-plus]
flavours = "funautic_fancy"
[metafile.chatanimation]
flavours = "funautic_fancy"
[metafile.cherished-worlds]
flavours = "funautic_fancy"
[metafile.chatanimation]
flavours = "funautic_fancy"
[metafile.cherished-worlds]
flavours = "funautic_fancy"
[metafile.detail-armor-bar-reconstructed]
flavours = "funautic_fancy"
[metafile.effectual]
flavours = "funautic_fancy"
[metafile.enchanted-fishing-line]
flavours = "funautic_fancy"
[metafile.entity-model-features]
flavours = "funautic_fancy"
[metafile.entity-texture-features-fabric]
flavours = "funautic_fancy"
[metafile.explosive-enhancement-reforged]
flavours = "funautic_fancy"
[metafile.immersive-ui]
flavours = "funautic_fancy"
[metafile.itemphysic-lite]
flavours = "funautic_fancy"
[metafile.make_bubbles_pop]
flavours = "funautic_fancy"
[metafile.particle-effects]
flavours = "funautic_fancy"
[metafile.particle-rain]
flavours = "funautic_fancy"
[metafile.particular-reforged]
flavours = "funautic_fancy"
[metafile.perception]
flavours = "funautic_fancy"
[metafile.polytone]
flavours = "funautic_fancy"
[metafile.smooth-gui]
flavours = "funautic_fancy"
[metafile.subtle-effects]
flavours = "funautic_fancy"
[metafile.tiny-item-animations]
flavours = "funautic_fancy"
[metafile.visuality-forge]
flavours = "funautic_fancy"
[metafile.wakes-reforged]
flavours = "funautic_fancy"

[metafile.atmospherics]
flavours = "atmospherics_on"

[metafile.aeronautics-wind-sound]
flavours = "sound_on"
[metafile.ambientsounds]
flavours = "sound_on"
[metafile.create-rolling-tones]
flavours = "sound_on"
[metafile.dripsounds]
flavours = "sound_on"
[metafile.more-sounds]
flavours = "sound_on"
[metafile.music-notification]
flavours = "sound_on"
[metafile.pf-neoforge]
flavours = "sound_on"
[metafile.presence-footsteps-x-sable]
flavours = "sound_on"
[metafile.sound-physics-aeronautics]
flavours = "sound_on"
[metafile.sound-physics-remastered]
flavours = "sound_on"
[metafile.sound]
flavours = "sound_on"

[metafile.aero_cam_sync]
flavours = "camera_tweak_on"
[metafile.cameraoverhaul]
flavours = "camera_tweak_on"

[metafile.boat-item-view]
flavours = "tweak_client_on"
[metafile.cleancut]
flavours = "tweak_client_on"
[metafile.client-tweaks]
flavours = "tweak_client_on"
[metafile.inventory-hud-forge]
flavours = "tweak_client_on"
[metafile.inventory-profiles-next]
flavours = "tweak_client_on"
[metafile.jump-over-fences]
flavours = "tweak_client_on"

[metafile.clean-tooltips]
flavours = "tooltips_on"
[metafile.create-package-tooltip]
flavours = "tooltips_on"
[metafile.obscure-tooltips]
flavours = "tooltips_on"

[metafile.colorwheel-patcher]
flavours = "shader"
[metafile.colorwheel]
flavours = "shader"
[metafile.createbetterfps]
flavours = "shader"
[metafile.irisshaders]
flavours = "shader"

[metafile.createsoftmotion]
flavours = "tweak_motion_on"
[metafile.a-good-place]
flavours = "tweak_motion_on"

[metafile.emf-compat-core]
flavours = "emf_comp_on"
[metafile.emf-compat-create]
flavours = "emf_comp_on"
[metafile.emf-compat-quark]
flavours = "emf_comp_on"

[metafile.in-game-account-switcher]
flavours = "admintools_on"
[metafile.observable]
flavours = "admintools_on"
[metafile.spark]
flavours = "admintools_on"

[metafile.punchy-fpa]
flavours = "punchy_on"

[metafile.distanthorizons]
flavours = "dh_on"