# Base Pack
[flavor_groups.funautic]
name = "Funautic Pack Choices"
description = "from the ashes became a muara"
side = "both"
[[flavor_groups.funautic.choices]]
id = "funautic_base"
name = "Base Version"
description = "Versi basic cuman mod yang penting aja, cocok buat yang mau main di server SMP"
[[flavor_groups.funautic.choices]]
id = "funautic_fancy"
name = "Fancy Version"
description = "Versi fancy dengan lebih banyak fitur dan visual yang menarik"

# Shader Choices
[flavor_groups.shader]
name = "Shader Choices"
description = "Only Shader dan optimasinya"
side = "client"
[[flavor_groups.shader.choices]]
id = "noshader"
name = "NO Shader"
description = "Tanpa Shader"
[[flavor_groups.shader.choices]]
id = "shader"
name = "Iris Shader"
description = "Shader dan optimasinya"

# Button Choice
[flavor_groups.dh]
name = "Distant Horizon"
side = "client"
choices = ["dh_off", "dh_on"]
description = "Menambahkan Chunk View Lebih jauh"
[flavor_groups.camtweak]
name = "Camera Tweaks"
side = "client"
choices = ["camtweak_off", "camtweak_on"]
description = "Tweak View agar lebih Immersive saat bermain"
[flavor_groups.cltweak]
name = "Client Tweaks"
side = "client"
choices = ["cltweak_off", "cltweak_on"]
description = "Pair dengan Punchy. Tweak Inventory, HUD Inventory, dan tweak kecil seperti off hand torch only tools"
[flavor_groups.soundtweak]
name = "Immersive Sounds"
side = "client"
choices = ["soundtweak_off", "soundtweak_on"]
description = "Immersive Sound seperti kicauan burung maupun item di inventory"
[flavor_groups.atmospherics]
name = "Atmospherics"
side = "client"
choices = ["atmospherics_off", "atmospherics_on"]
description = "Atmospheric, jangan pair sama DH jika View Distance kamu rendah"
[flavor_groups.tooltips]
name = "Tooltips"
side = "client"
choices = ["tooltips_off", "tooltips_on"]
description = "Tooltips item, informasi yang cukup berguna jika sedang hover"
[flavor_groups.motitweak]
name = "Tweak Motion"
side = "client"
choices = ["motitweak_off", "motitweak_on"]
description = "Motion Tweak untuk place block dan Propeler aeronautic"
# [flavor_groups.emftweak]
# name = "EMF Compability"
# side = "client"
# choices = ["emftweak_off", "emftweak_on"]
[flavor_groups.punchy]
name = "Punchy"
side = "client"
choices = ["punchy_off", "punchy_on"]
description = "Punchy, animasi 1st person"
[flavor_groups.admintools]
name = "Admin Tools"
side = "client"
choices = ["admintools_off", "admintools_on"]
description = "Tools khusus Admin"

# Modlist
[metafile.3dskinlayers]
flavors = "funautic_fancy"
[metafile.better-clouds]
flavors = "funautic_fancy"
[metafile.blur-plus]
flavors = "funautic_fancy"
[metafile.chatanimation]
flavors = "funautic_fancy"
[metafile.cherished-worlds]
flavors = "funautic_fancy"
[metafile.detail-armor-bar-reconstructed]
flavors = "funautic_fancy"
[metafile.effectual]
flavors = "funautic_fancy"
[metafile.enchanted-fishing-line]
flavors = "funautic_fancy"
[metafile.entity-model-features]
flavors = "funautic_fancy"
[metafile.entity-texture-features-fabric]
flavors = "funautic_fancy"
[metafile.explosive-enhancement-reforged]
flavors = "funautic_fancy"
[metafile.immersive-ui]
flavors = "funautic_fancy"
[metafile.itemphysic-lite]
flavors = "funautic_fancy"
[metafile.make_bubbles_pop]
flavors = "funautic_fancy"
[metafile.particle-effects]
flavors = "funautic_fancy"
[metafile.particle-rain]
flavors = "funautic_fancy"
[metafile.particular-reforged]
flavors = "funautic_fancy"
[metafile.perception]
flavors = "funautic_fancy"
[metafile.polytone]
flavors = "funautic_fancy"
[metafile.smooth-gui]
flavors = "funautic_fancy"
[metafile.subtle-effects]
flavors = "funautic_fancy"
[metafile.tiny-item-animations]
flavors = "funautic_fancy"
[metafile.visuality-forge]
flavors = "funautic_fancy"
[metafile.wakes-reforged]
flavors = "funautic_fancy"
[metafile.create-aeronautics-vapor-trails]
flavors = "funautic_fancy"

[metafile.atmospherics]
flavors = "atmospherics_on"

[metafile.aeronautics-wind-sound]
flavors = "soundtweak_on"
[metafile.ambientsounds]
flavors = "soundtweak_on"
[metafile.dripsounds]
flavors = "soundtweak_on"
[metafile.more-sounds]
flavors = "soundtweak_on"
[metafile.music-notification]
flavors = "soundtweak_on"
[metafile.pf-neoforge]
flavors = "soundtweak_on"
[metafile.presence-footsteps-x-sable]
flavors = "soundtweak_on"
[metafile.sound-physics-aeronautics]
flavors = "soundtweak_on"
[metafile.sound-physics-remastered]
flavors = "soundtweak_on"
[metafile.sound]
flavors = "soundtweak_on"

[metafile.aero_cam_sync]
flavors = "camtweak_on"
[metafile.cameraoverhaul]
flavors = "camtweak_on"

[metafile.boat-item-view]
flavors = "cltweak_on"
[metafile.cleancut]
flavors = "cltweak_on"
[metafile.client-tweaks]
flavors = "cltweak_on"
[metafile.inventory-hud-forge]
flavors = "cltweak_on"
[metafile.inventory-profiles-next]
flavors = "cltweak_on"
[metafile.jump-over-fences]
flavors = "cltweak_on"

[metafile.clean-tooltips]
flavors = "tooltips_on"
[metafile.create-package-tooltip]
flavors = "tooltips_on"
[metafile.obscure-tooltips]
flavors = "tooltips_on"

[metafile.colorwheel-patcher]
flavors = "shader"
[metafile.colorwheel]
flavors = "shader"
[metafile.createbetterfps]
flavors = "shader"
[metafile.irisshaders]
flavors = "shader"

[metafile.createsoftmotion]
flavors = "motitweak_on"
[metafile.a-good-place]
flavors = "motitweak_on"

# [metafile.emf-compat-core]
# flavors = "emftweak_on"
# [metafile.emf-compat-create]
# flavors = "emftweak_on"

[metafile.in-game-account-switcher]
flavors = "admintools_on"
[metafile.observable]
flavors = "admintools_on"
[metafile.spark]
flavors = "admintools_on"

[metafile.punchy-fpa]
flavors = "punchy_on"

[metafile.distanthorizons]
flavors = "dh_on"