name: Deploy packwiz pack to GitHub Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v7
        continue-on-error: true
        with:
          ref: main
          path: main

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Refresh Packwiz Hashes
        run: |
          if [ -d "main/modpack" ]; then
            go install github.com/packwiz/packwiz@latest
            
            cd main/modpack

            sed -i '/no-internal-hashes/d' pack.toml
            packwiz refresh

          else
            exit 1
          fi

      - name: Prepare output
        run: |
          mkdir -p out
          echo "<h1>Modpack Repository</h1><p>Status: 200 OK</p>" > out/index.html

          mkdir -p out/modpack

          if [ -d "main/modpack" ]; then
            cp -r main/modpack/* out/modpack/
          else
            exit 1
          fi

          if [ -d "main/mmcpack" ]; then
            (cd main/mmcpack && zip -q -r ../../out/funautic.zip .)
          else
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "out"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
